# Use an official R runtime as a parent image
FROM r-base:latest

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN R -e "install.packages(c('tidyverse', 'devtools', 'deldir', 'dplyr', 'gganimate', 'ggfootball', 'ggforce', 'ggplot2', 'ggrepel', 'igraph', 'readr', 'ngscleanR', 'nflverse', 'gt', 'gtExtras', 'patchwork'), repos='http://cran.rstudio.com/')"

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.R when the container launches
CMD ["Rscript", "TacklesInSpace.R"]